services:
  nginx:
    image: nginx:latest
    ports:
      - 8083:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
  db:
    ports:
      - 5432:5432
    container_name: postgres_cont
    image: postgres
    environment:
      - POSTGRES_DB=infobip_project_db
      - POSTGRES_PASSWORD=bazepodataka
      - POSTGRES_USER=admin
    volumes:
      - /home/adrian/postgres_container_data:/var/lib/postgresql/data
    restart: always

#  backend:
#    build: .
#    container_name: infobip_app_cont
#    image: infobip_app_img
#    ports:
#      - 8089:8089
#    depends_on:
#      - db
#    restart: always

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    depends_on:
      - db
    restart: always

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - db
    restart: always